# enable H2 console at localhost:8080/h2-console
spring:
  h2.console:
    enabled: true
    path: /h2-console
  output.ansi.enabled: always

logging.level.org.hibernate:
  SQL: DEBUG
  type: TRACE
#  type.descriptor.sql.BasicBinder: TRACE
